### ISSUE TITLE
Use of External Libraries

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [cloudflare-internship-2020/internship-application-systems#1]
I am very excited that Cloudflare is hosting this task for summer interns. However, I think there is an important aspect of this task that should be clarified: are external libraries (outside of the standard libraries that come with the languages) explicitly allowed? If so, how will they be bundled with our source code?

Thanks!

**Comment by sudopluto** [comment]
just wanted to add:

for C/C++, could a header library like [catch](https://github.com/catchorg/Catch2) be used for testing?

iirc, go and rust both have testing as part of stdlib, while C/C++ folk would have to roll their own if they wanted to test

**Comment by cloudflare-internship-2020** [comment]
@sudopluto , feel free to use catch.

**Comment by cloudflare-internship-2020** [comment]
@Daniel-Liu-c0deb0t , whatever you submit should be easy to build so please do not include binaries.  You are allowed to use other libraries as long as they build as part of your submission.
