### ISSUE TITLE
Decoupling Sending and Receiving

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [cloudflare-internship-2020/internship-application-systems#3]
From the task statement, it is unclear whether sending the ping and receiving the ping should happen *sequentially* (send -> wait -> receive -> send next ping -> wait -> receive next ping...) or *concurrently*. It seems that the Linux `ping` command adopts the concurrent paradigm (packets can be received out of order), while other similar programs/reimplementations use the sequential paradigm (likely for its simplicity). For this task, is there a preference on which paradigm we should implement?

Sorry if this is a bit unclear, since I am trying to be vague to not give away any hints, etc.

**Comment by cloudflare-internship-2020** [comment]
On a network everything is concurrent. Packets can arrive late and out of
order. It is up to the implementer to decide how to treat those packets.

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey, thanks for answering. Sorry, I've realized that I was unclear in the question. I meant that in some ping implementations they explicitly wait to receive a packet before moving on to send the next packet. However, given your reply it seems that we shouldn't do this.
